"""Add profile fields

Revision ID: 58b05f0e1fc8
Revises: 9d42fe5cfcd6
Create Date: 2026-05-30 19:27:29.981854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b05f0e1fc8'
down_revision: Union[str, Sequence[str], None] = '9d42fe5cfcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilePhoto', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('companyAddress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('companyPhone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('companyEmail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('companyWebsite', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('defaultFont', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('defaultBorderColor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('defaultLineSpacing', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('defaultLetterSpacing', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('defaultLetterSpacing')
        batch_op.drop_column('defaultLineSpacing')
        batch_op.drop_column('defaultBorderColor')
        batch_op.drop_column('defaultFont')
        batch_op.drop_column('companyWebsite')
        batch_op.drop_column('companyEmail')
        batch_op.drop_column('companyPhone')
        batch_op.drop_column('companyAddress')
        batch_op.drop_column('designation')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('profilePhoto')

    # ### end Alembic commands ###
