"""Add thumbnail, premium, and layout type to templates

Revision ID: 99288548fc74
Revises: 58b05f0e1fc8
Create Date: 2026-05-30 20:21:53.187721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99288548fc74'
down_revision: Union[str, Sequence[str], None] = '58b05f0e1fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnailUrl', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('isPremium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('layoutType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('layoutType')
        batch_op.drop_column('isPremium')
        batch_op.drop_column('thumbnailUrl')

    # ### end Alembic commands ###
