"""initial sqlite schema

Revision ID: 9d42fe5cfcd6
Revises: 
Create Date: 2026-05-30 12:41:21.417841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d42fe5cfcd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('baseJSON', sa.JSON(), nullable=False),
    sa.Column('isReusable', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashedPassword', sa.String(), nullable=False),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('company_branding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('logoUrl', sa.String(), nullable=True),
    sa.Column('primaryColor', sa.String(), nullable=True),
    sa.Column('secondaryColor', sa.String(), nullable=True),
    sa.Column('letterheadUrl', sa.String(), nullable=True),
    sa.Column('signatureUrl', sa.String(), nullable=True),
    sa.Column('sealUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('candidateDetails', sa.JSON(), nullable=False),
    sa.Column('contentJSON', sa.JSON(), nullable=False),
    sa.Column('brandingId', sa.String(), nullable=True),
    sa.Column('exportUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brandingId'], ['company_branding.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('documentId', sa.String(), nullable=True),
    sa.Column('recipientEmail', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sentAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documentId'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_edits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=True),
    sa.Column('documentId', sa.String(), nullable=True),
    sa.Column('lastEditedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documentId'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_edits')
    op.drop_table('email_logs')
    op.drop_table('documents')
    op.drop_table('company_branding')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('templates')
    # ### end Alembic commands ###
